name: Netree
on:
  push:
  pull_request:
    branches: [ main ]
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/netree
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongodb-version: ['6.0', '6.3']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install yarn
        uses: Borales/actions-yarn@v4.2.0
      - name: Use MongoDB from GitHub actions
        uses:  supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: yarn run serve