name: Netree
on:
  push:
  pull_request:
    branches: [ main ]
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint